export default [
  {
    id: 1,
    name: "Treasure of East Side",
    info: "Below the castle is a mosque, formerly the Armenian church known as Surb Arak'elots, the Church of the Holy Apostles. Built in the 930s, it has a tetraconch plan (a square with four semicircular apses) surmounted by a spherical dome on a cylindrical drum. On the exterior, the drum of contains bas-relief depictions of twelve figures, usually interpreted as representing the Twelve Apostles. The dome has a conical roof. The church was converted to a mosque in 1579, and then converted into a Russian Orthodox church in the 1880s. The Russians built porches in front of the church's three entrances, and an elaborate clocktower (now demolished) next to the church. The church was used as a warehouse from the 1930s, and it housed a small museum from 1963 until the late 1970s. Then the building was left to itself for about two decades, until it was converted into a mosque in 1993. In the same district of Kars are two other ruined Armenian churches. A Russian church from the 1900s was converted to a mosque in the 1980s after serving as a school gymnasium.The Grand Mosque of Kars is the largest historic mosque in the city. Built by the Seljuks, it was restored by the Ottomans in 1579.The Taşköprü (Stone Bridge) is a bridge over the Kars river, built in 1725. Close to the bridge are three old bath-houses, none of them operating any longer.",
    img: "https://cdng.jollytur.com/files/packagephoto/packagephotos/3b424197-2436-4310-9076-98f38787b3f2-1024.jpg",
    price: "$500",
  },
  {
    id: 2,
    name: "Capadocia",
    info: "The area is a popular tourist destination, as it has many areas with unique geological, historic, and cultural features.Touristic Cappadocia includes 4 cities: Nevşehir, Kayseri, Aksaray and Niğde.The region is located southwest of the major city Kayseri, which has airline and railway service to Ankara and Istanbul and other cities.The most important towns and destinations in Cappadocia are Ürgüp, Göreme, Ihlara Valley, Selime, Guzelyurt, Uçhisar, Avanos and Zelve. Among the most visited underground cities are Derinkuyu, Kaymakli, Gaziemir and Ozkonak. The best historic mansions and cave houses for tourist stays are in Ürgüp, Göreme, Guzelyurt and Uçhisar.Hot-air ballooning is very popular in Cappadocia and is available in Göreme. Trekking is enjoyed in Ihlara Valley, Monastery Valley (Guzelyurt), Ürgüp and Göreme.Sedimentary rocks formed in lakes and streams and ignimbrite deposits that erupted from ancient volcanoes approximately 9 to 3 million years ago, during the late Miocene to Pliocene epochs, underlie the Cappadocia region. The rocks of Cappadocia near Göreme eroded into hundreds of spectacular pillars and minaret-like forms. People of the villages at the heart of the Cappadocia Region carved out houses, churches and monasteries from the soft rocks of volcanic deposits. Göreme became a monastic centre in 300–1200 AD.The first period of settlement in Göreme goes back to the Roman period. The Yusuf Koç, Ortahane, Durmus Kadir and Bezirhane churches in Göreme, and houses and churches carved into rocks in the Uzundere, Bağıldere and Zemi Valleys, all illustrate history and can be seen today. The Göreme Open Air Museum is the most visited site of the monastic communities in Cappadocia (see Churches of Göreme, Turkey) and is one of the most famous sites in central Turkey. The complex contains more than 30 carved-from-rock churches and chapels, some having superb frescoes inside, dating from the 9th century to the 11th century.",
    img: "https://cdng.jollytur.com/files/packagephoto/packagephotos/717602ef-86d0-421e-a680-f14f4d2ed33e-1024.jpg",
    price: "$500",
  },
  {
    id: 3,
    name: "Assos",
    info: "The city was founded from 1000 to 900 BC by Aeolian colonists from Lesbos, who specifically are said to have come from Methymna. The natural cleavage of the rock into joint planes had already scarped out shelves which it was comparatively easy for human labour to shape.The settlers built a Doric Temple to Athena on top of the crag in 530 BC. From this temple Hermias of Atarneus, a student of Plato, ruled Assos, the Troad and Lesbos for a period of time, under which the city experienced its greatest prosperity. Strangely, Hermias was actually the slave of the ruler of Atarneus. Under his rule, he encouraged philosophers to move to the city. As part of this, in 348 BC Aristotle came here and married King Hermeias's niece, Pythia, before leaving for Lesbos three years later in 345 BC. This 'golden period' of Assos ended several years later when the Persians arrived, and subsequently tortured Hermias to death.The Persians were driven out by Alexander the Great in 334 BC. Between 241 and 133 BC, the city was ruled by the Kings of Pergamon. However, in 133 BC, the Pergamons lost control of the city as it was absorbed by the Roman empire.According to Christian tradition, St. Paul also visited the city during his third missionary journey through Asia Minor, which was between 53-57 AD, on his way to Mytilene on the island of Lesbos. Acts 20 records that Luke the Evangelist and his companions 'we' went ahead to the ship and sailed to Assos, there intending to take Paul on board and when he met us at Assos, we took him on board and came to Mitylene.From this period onwards, Assos shrunk to a small village, as it has remained ever since. Ruins around Assos continue to be excavated.The pillars from the ancient port lay in the harbor for over a millennia. Eventually they were probably sold.In the early 1900s an attempt was made to move the contents of the Temple of Athena. Much of the art has been moved to museums like the Louvre. The art found includes pictures both of mythical creatures and heraldic events.In 2018, archaeologists discovered a Hellinistic undamaged family grave. the name Aristios was written on the cover of the grave. The grave belonged to a family of 21. One of the family members was buried normally, while the remaining 20 were cremated and their ashes were placed inside urn-like vases. The lids were sealed off with cement in order to prevent any foreign substance getting inside the urns.",
    img: "https://cdng.jollytur.com/files/packagephoto/packagephotos/096604b7-f457-47ed-b347-e853c21f6095-1024.jpg",
    price: "$500",
  },
  {
    id: 4,
    name: "Lycia",
    info: "Although the 2nd-century BC dialogue Erōtes found the cities of Lycia interesting more for their history than for their monuments, since they have retained none of their former splendor, many relics of the Lycians remain visible today. These relics include the distinctive rock-cut tombs in the sides of cliffs. The British Museum in London grabbed one of the best collections of Lycian artifacts. Letoon, an important center in Hellenic times of worship for the goddess Leto and her twin children, Apollo and Artemis, and nearby Xanthos, ancient capital of Lycia, constitute a UNESCO World Heritage site.Turkey's first waymarked long-distance footpath, the Lycian Way, follows part of the coast of the region. The establishment of the path was a private initiative by a British/Turkish woman called Kate Clow. It is intended to support sustainable tourism in smaller mountain villages which are in the process of depopulation. Since it is mainly walked in March – June and Sept–Nov, it also has lengthened the tourism season. The Turkish Culture and Tourism Ministry promotes the Lycian coast as part of the Turkish Riviera or the Turquoise Coast, but the most important part of this is further west near Bodrum. This coast features rocky or sandy beaches at the bases of cliffs and settlements in protected coves that cater to the yachting industry.",
    img: "https://cdng.jollytur.com/files/packagephoto/packagephotos/a0884f26-6324-4dff-b963-49c38020f19d-1024.jpg",
    price: "$500",
  },
  {
    id: 5,
    name: "Gobekli Tepe",
    info: "Before being documented by archaeologists, the hill Göbekli Tepe stands on, known locally in Kurdish as Girê Mirazan or Xerabreşk, was considered a sacred place. The archaeological site was first noted in a survey conducted by Istanbul University and the University of Chicago in 1963. American archaeologist Peter Benedict identified lithics collected from the surface of the site as belonging to the Aceramic Neolithic, but mistook stone slabs the upper parts of the T-shaped pillars for grave markers, postulating that the prehistoric phase was overlain by a Byzantine cemetery. The hill had long been under agricultural cultivation, and generations of local inhabitants had frequently moved rocks and placed them in clearance piles, which may have disturbed the upper layers of the site. At some point attempts had been made to break up some of the pillars, presumably by farmers who mistook them for ordinary large rocks. In October 1994, German archaeologist Klaus Schmidt, who had previously been working at Nevalı Çori, was looking for evidence of similar sites in the area and decided to reexamine the location described by the Chicago researchers in 1963. Asking in nearby villages about hills with flint, he was guided to Göbekli Tepe by Mahmut and İbrahim Yıldız, the farmers who owned the land the site was situated on. Mahmut Yıldız and his father had previously discovered finds while plowing there, which they reported to the local museum. Having found similar structures at Nevalı Çori, Schmidt recognized the possibility that the stone slabs were not Byzantine grave markers as supposed by Benedict, but the tops of prehistoric megaliths. He began excavations the following year and soon unearthed the first of the huge T-shaped pillars. Yıldız went on to work on the excavations and serve as the site's guard. Schmidt continued to direct excavations at the site on behalf of the Şanlıurfa Museum and the German Archaeological Institute (DAI) until his death in 2014. Since then, the DAI's research at the site has been coordinated by Lee Clare. As of 2021, work on the site is conducted jointly by Istanbul University, the Şanlıurfa Museum, and the DAI, under the overall direction of Necmi Karul. Recent excavations have been more limited than Schmidt's, focusing on detailed documentation and conservation of the areas already exposed.",
    img: "https://cdng.jollytur.com/files/packagephoto/packagephotos/3125395a-ca15-471f-a0ec-38c2f95edec7-1024.jpg",
    price: "$500",
  },
  {
    id: 6,
    name: "Three Tombs",
    info: "The cluster of three tomb towers known as Üç Kümbetler (“Three Tombs”) is located just south of the city center of modern Erzurum. In the medieval period, the tombs would have lay outside the city walls not far from Tabriz Kapısı (Tabriz Gate). The largest tomb, locally referred to as the Tomb of Emir Saltuk, is tentatively dated to the late twelfth century/sixth century AH. Based on stylistic comparisons, scholars date the other two tombs that are unmarked and unnamed to the fourteenth century/eighth century AH.All three tomb towers are based on the same type of plan: a cylindrical or polygonal shaft with a conical roofs. The Tomb of Emir Saltuk is distinguished by its octagonal plan with sides rising to a short gable under its roof, which is squatter than the others. The other two tombs have cylindrical bodies decorated with a series of blind arches and conical roofs.",
    img: "https://cdng.jollytur.com/files/packagephoto/packagephotos/4a23ab13-3121-4933-8957-c20b0755d48f-1024.jpg",
    price: "$500",
  },
];
